# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb943080cdcf1754d0795c63e15110019c2b4420d36cdd964ccef4cfb68413138a725b34b7b110d4d88877e59509ebcc15569bf68bf14a6c0e40aafacb092302

test:
  secret_key_base: 80a616becbb7c36ba3820b22b9f8567a4588a487f6ab06a21dc99db5a22f82488964ac893db301852a3becfd45db8ffcbcd959ea05c0407d66e89815641b4de5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
